# .streamlit/secrets.toml

[cloudinary]
cloud_name = "dt2pqodbr"
api_key = "631657747531236"
api_secret = "yqbYLxbtfZdM3DcX08CnHKKx5DI"

[google_service_account]
# You can also store your service account JSON keys here as one string if preferred
# For now, let's assume you keep a local file "service_account.json"
