@st.cache_resource
def connect_sheets():
    scope = ["https://www.googleapis.com/auth/spreadsheets"]

    creds = Credentials.from_service_account_info(
        st.secrets["google_service_account"],
        scopes=scope
    )

    client = gspread.authorize(creds)
    return client.open_by_key("1KVQsImewzbcPt5xGGKZWRw2_amILgsuFmt-On58gyac")
